<?php

namespace EntityAppBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * 
	 *
	 * @param integer
	 */
	public function findLastNOrderedById($number)
	{
		return $this->getEntityManager()
		->createQuery(
				'SELECT c FROM EntityAppBundle:Commande c ORDER BY c.id DESC LIMIT ' . $number
				)
				->getResult();
	}
	
	/**
	 *
	 *
	 */
	public function findOneByCurrent($foo= null)
	{
		return $this->getEntityManager('rep')
		->createQuery(
				'SELECT c FROM EntityAppBundle:Commande c where actif=1'
				)
				->getResult();
	}	
}
